create table
  public.user_splits (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    "userID" uuid null default auth.uid (),
    "splitID" uuid null default gen_random_uuid (),
    split_data jsonb null,
    constraint user_splits_pkey primary key (id),
    constraint user_splits_userID_fkey foreign key ("userID") references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;